# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Ensure uWSGI directory exists
  file:
    path: "/etc/uwsgi/"
    state: directory
    mode: "0711"

- name: Apply uWSGI configuration
  config_template:
    src: "keystone-uwsgi.ini.j2"
    dest: "/etc/uwsgi/{{ item }}.ini"
    mode: "0744"
    config_overrides: "{{ keystone_uwsgi_ini_overrides }}"
    config_type: ini
  with_items: "{{ keystone_wsgi_program_names }}"
  notify:
    - Restart uWSGI on first node
    - Restart uWSGI on other nodes

- include: "keystone_init_{{ ansible_service_mgr }}.yml"
  vars:
    program_name: "{{ keystone_wsgi_public_program_name }}"
    service_name: "{{ keystone_wsgi_public_program_name }}"
    system_user: "{{ keystone_system_user_name }}"
    system_group: "{{ keystone_system_group_name }}"
    service_home: "{{ keystone_system_user_home }}"

- include: "keystone_init_{{ ansible_service_mgr }}.yml"
  vars:
    program_name: "{{ keystone_wsgi_admin_program_name }}"
    service_name: "{{ keystone_wsgi_admin_program_name }}"
    system_user: "{{ keystone_system_user_name }}"
    system_group: "{{ keystone_system_group_name }}"
    service_home: "{{ keystone_system_user_home }}"
