---
    - name: Installation and setup of Keystone
      hosts: keystone_all
      user: root
      pre_tasks:
        - name: Create DB for service
          mysql_db:
            login_user: "root"
            login_password: "secrete"
            login_host: "localhost"
            name: "{{ keystone_galera_database }}"
            state: "present"
          delegate_to: "{{ keystone_galera_address }}"
          when: inventory_hostname == groups['keystone_all'][0]
          no_log: true
        - name: Grant access to the DB for the service
          mysql_user:
            login_user: "root"
            login_password: "secrete"
            login_host: "localhost"
            name: "{{ keystone_galera_database }}"
            password: "{{ keystone_container_mysql_password }}"
            host: "{{ item }}"
            state: "present"
            priv: "{{ keystone_galera_database }}.*:ALL"
          with_items:
            - "localhost"
            - "%"
          delegate_to: "{{ keystone_galera_address }}"
          when: inventory_hostname == groups['keystone_all'][0]
          no_log: true
      roles:
        - { role: "os_keystone", tags: [ "os-keystone" ] }
      vars:
        external_lb_vip_address: 10.100.100.102
        internal_lb_vip_address: 10.100.100.102
        keystone_galera_address: 10.100.100.101
        keystone_galera_database: keystone
        keystone_venv_tag: "testing"
        keystone_developer_mode: true
        keystone_git_install_branch: master
        keystone_auth_admin_password: "SuperSecretePassword"
        keystone_service_password: "secrete"
        keystone_oslomsg_rpc_password: "secrete"
        keystone_oslomsg_notify_password: "secrete"
        keystone_container_mysql_password: "SuperSecrete"
        keystone_oslomsg_rpc_transport: rabbit
        keystone_oslomsg_rpc_servers: 10.100.100.101
        keystone_oslomsg_rpc_port: 5671
        keystone_oslomsg_rpc_use_ssl: true
        keystone_oslomsg_rpc_userid: keystone
        keystone_oslomsg_rpc_vhost: /keystone
        keystone_oslomsg_notify_transport: rabbit
        keystone_oslomsg_notify_servers: 10.100.100.101
        keystone_oslomsg_notify_port: 5671
        keystone_oslomsg_notify_use_ssl: true
        keystone_oslomsg_notify_userid: keystone
        keystone_oslomsg_notify_vhost: /keystone
        galera_client_drop_config_file: false
